### PR TITLE
Replace cypress fork with plugin

### PR DESCRIPTION
**Pull request by ryanjduffy**
* Adds `"Replay Firefox"` as a browser via a plugin so you can record with:
```bash
yarn cypress run --spec cypress/tests/ui/user-settings.spec.ts  --browser "Replay Firefox"
```

Recordings can be uploaded using the CLI

### CODE REVIEW

**Comment by ryanjduffy** [comment]
@bhackett1024 + @ceceliacreates - far from a Cypress expert but this seems like a reasonable approach. It follows the same architecture I've used for `playwright-config` and `puppeteer-config` by installing the browser as part of `npm install`-ing the plugin and then the plugin injects the browser path into the test runtime.

Thoughts / concerns?

**Review by jasonLaster — COMMENTED** [review]
Looks great. The docs will write themselves :)

**Comment by bhackett1024** [comment]
This looks good but it would be nice to have a better understanding of how this will work when recording multiple spec files.  Will this a) produce a single recording containing all of the tests from those specs, b) re-run specs that failed to produce a smaller recording, or c) run each spec separately.  One other thing the @recordreplay/cypress package does is allow recording individual tests which failed, instead of entire spec files.  I'm not sure yet how important that behavior is but it seems like spec files could in some cases get pretty large.  Are we planning on replacing the @recordreplay/cypress fork with a plugin as the only and/or recommended way, or support both use cases?

**Review by bhackett1024 — APPROVED** [review]

**Comment by ryanjduffy** [comment]
@bhackett1024 - Thanks for the feedback. I think some further configuration options are warranted here. Right now, this will add support for running all of the tests with Replay and uploading either all or only failed specs. However, I think it should be possible to add options that would re-run failed tests or specs with replay and then upload those as you've implemented with the fork.

In the medium term, I hope we can sunset the cypress fork and just use the plugin since it'll be easier to maintain and fit into customer workflows more easily.

**Comment by bhackett1024** [comment]
Sounds good, I agree a plugin would be a better option than the fork for integrating with customer workflows.  Before switching to that entirely though we should make sure we have enough expressiveness for the UX we'd like.  When developing the cypress fork I noticed that there is a long startup time for cypress so it makes the most sense to run multiple spec files at once (e.g. the entire project's spec files), but if that is done using replay it will (a) produce a huge recording we will have difficulty replaying, and (b) use more memory than a regular firefox browser, which could cause problems for users (see https://github.com/RecordReplay/backend/issues/4307 for more).  For these reasons the fork uses the regular browser when running the target spec files, and only re-runs tests we want a recording for using replay.

I guess a third option would be to do something similar to https://github.com/RecordReplay/jest, and provide a package that is a wrapper around the cypress CLI instead of a fork of it.  The only modifications our cypress fork makes are to the CLI's behavior so this wouldn't be too hard if it would be simplify integration with customer workflows.

**Comment by jasonLaster** [comment]
Sharing the Cypress 10 branch which should launch in the next couple of weeks.
https://github.com/cypress-io/cypress/tree/10.0-release

**Review by jasonLaster — APPROVED** [review]

**Comment by ryanjduffy** [comment]
I've updated this to use cypress 10 and the new `@replayio/cypress` plugin but I haven't addressed any of @bhackett1024 's concerns above. I published `@replayio/cypress` so we have a alpha version to experiment with here or with early design partners. I'm going to go ahead and merge this PR to aid our testing and eval but we can revert if we're not able to achieve the desired DX with the plugin architecture.

**Comment by bhackett1024** [comment]
> I've updated this to use cypress 10 and the new `@replayio/cypress` plugin but I haven't addressed any of @bhackett1024 's concerns above. I published `@replayio/cypress` so we have a alpha version to experiment with here or with early design partners. I'm going to go ahead and merge this PR to aid our testing and eval but we can revert if we're not able to achieve the desired DX with the plugin architecture.

The concerns I raised earlier are less of a problem now.  We now support long recordings and shouldn't have memory usage problems while creating them.  I think we should focus on making it a good experience to record all tests while using replay and make sure we can do so reliably and make it easy to focus on the part of the recording where tests failed.

**Pull request merged**
